# Generated by Django 4.2.7 on 2024-01-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('resume', models.FileField(null=True, upload_to='files')),
                ('experience', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('others', 'others')], default='male', max_length=20)),
            ],
        ),
    ]
